from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from datetime import datetime

db = SQLAlchemy()


class User(UserMixin, db.Model):
    """Single table for both Admin and Recruiter, differentiated by role."""
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(255), nullable=False)
    role = db.Column(db.String(20), nullable=False)  # 'admin' or 'recruiter'
    is_active_flag = db.Column(db.Boolean, default=True)  # Admin can enable/disable recruiter
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    jobs = db.relationship("Job", backref="recruiter", lazy=True)

    # Flask-Login requires `is_active` property
    @property
    def is_active(self):
        return self.is_active_flag


class Job(db.Model):
    """A job posting created by a recruiter, with a job description (JD)."""
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False)
    required_skills = db.Column(db.Text)  # comma separated, optional manual hint
    recruiter_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    resumes = db.relationship("Resume", backref="job", lazy=True, cascade="all, delete-orphan")


class Resume(db.Model):
    """An uploaded resume, scored & ranked against its Job's description."""
    id = db.Column(db.Integer, primary_key=True)
    job_id = db.Column(db.Integer, db.ForeignKey("job.id"), nullable=False)
    filename = db.Column(db.String(255), nullable=False)
    candidate_name = db.Column(db.String(200))
    raw_text = db.Column(db.Text)
    matched_keywords = db.Column(db.Text)   # comma separated overlap keywords
    score = db.Column(db.Float, default=0.0)        # similarity score 0-100
    rank = db.Column(db.Integer)                    # rank within the job (1 = best)
    status = db.Column(db.String(20), default="pending")  # pending/shortlisted/rejected
    interview_questions = db.Column(db.Text)         # newline separated, generated by AI
    uploaded_at = db.Column(db.DateTime, default=datetime.utcnow)
